### ISSUE TITLE
看官方文档还是没有明白device token怎么获取

### ISSUE THREAD

**Issue by pirately** [qy527145/openai_token#3]
看官方文档还是没有明白device token怎么获取，请问有没有对小白友好点的教程？最好是一键获取的

**Comment by qy527145** [comment]
可以用mitm抓包，具体教程可以看[这里](https://linux.do/t/topic/58580)

**Comment by leadscloud** [comment]
当前还有什么办法吗， 这个方法不行了。旧版本的ios app不能运行了。无法在ios设备上面通过mitm抓包获取

**Comment by qy527145** [comment]
越狱的ios设备可以抓包

**Comment by leadscloud** [comment]
现在chatgpt旧的iphone提示无法使用了，高版本的ios也无法越狱。
